//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered_coal
    {
        public int ID_coal { get; set; }
        public int ID_order { get; set; }
        public int ID_type_coal { get; set; }
        public int quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Type_coal Type_coal { get; set; }
    }
}
