//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_coal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type_coal()
        {
            this.Ordered_coal = new HashSet<Ordered_coal>();
        }
    
        public int ID_type_coal { get; set; }
        public int ID_city_coal { get; set; }
        public string Name_type { get; set; }
        public int Price { get; set; }
        public int Total_quantity_coal { get; set; }
    
        public virtual City_coal City_coal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordered_coal> Ordered_coal { get; set; }
    }
}
